# Generated by Django 2.2.17 on 2021-02-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('portfolio_name', models.CharField(blank=True, max_length=255, null=True)),
                ('campaign_type', models.CharField(blank=True, max_length=255, null=True)),
                ('campaign_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(blank=True, max_length=255, null=True)),
                ('budget', models.CharField(blank=True, max_length=255, null=True)),
                ('targeting_type', models.CharField(blank=True, max_length=255, null=True)),
                ('bidding_strategy', models.CharField(blank=True, max_length=255, null=True)),
                ('impressions', models.CharField(blank=True, max_length=255, null=True)),
                ('last_year_impressions', models.CharField(blank=True, max_length=255, null=True)),
                ('clicks', models.CharField(blank=True, max_length=255, null=True)),
                ('last_year_clicks', models.CharField(blank=True, max_length=255, null=True)),
                ('click_thru_rate_ctr', models.CharField(blank=True, max_length=255, null=True)),
                ('spend', models.CharField(blank=True, max_length=255, null=True)),
                ('last_year_spend', models.CharField(blank=True, max_length=255, null=True)),
                ('cost_per_click_cpc', models.CharField(blank=True, max_length=255, null=True)),
                ('last_year_cost_per_click_cpc', models.CharField(blank=True, max_length=255, null=True)),
                ('seven_day_total_orders', models.CharField(blank=True, max_length=255, null=True)),
                ('total_advertising_cost_of_sales_acos', models.CharField(blank=True, max_length=255, null=True)),
                ('total_return_on_advertising_Spend_roas', models.CharField(blank=True, max_length=255, null=True)),
                ('seven_day_total_sales', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
