# Generated by Django 2.2.17 on 2021-02-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
