# Generated by Django 2.2.17 on 2021-02-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210209_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='clicks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='impressions',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='last_year_clicks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='last_year_impressions',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='seven_day_total_orders',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='total_return_on_advertising_Spend_roas',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
    ]
